# Generated by Django 4.2.5 on 2023-10-05 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosexames',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitacaoexame',
            name='exame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exames.tiposexames'),
        ),
        migrations.AlterField(
            model_name='solicitacaoexame',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
